### Create a new User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "ahmed@gmail.com",
    "password": "ahmed!@#",
    "hacker/admin": "Will be ignored by whitelist: true"
}